"""empty message

Revision ID: 5c98fe893e90
Revises: 4641b7238459
Create Date: 2021-08-28 20:33:04.743095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c98fe893e90'
down_revision = '4641b7238459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('homeworld', sa.String(length=30), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('vehicle', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes')
    # ### end Alembic commands ###
